"""cfixing FK constraints

Revision ID: 86c89b00859d
Revises: 950702b6f1c4
Create Date: 2021-07-20 14:38:00.816975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c89b00859d'
down_revision = '950702b6f1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('url', sa.String(), nullable=True))
    op.drop_constraint('card_deck_id_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'deck', ['deck_id'], ['deck_id'])
    op.drop_column('card', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_deck_id_fkey', 'card', 'game', ['deck_id'], ['game_id'])
    op.drop_column('card', 'url')
    # ### end Alembic commands ###
